### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by UltimateBoi** [sssssssthedev/SmartClient#1]
Crashes on loading

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 08/02/22 19:37
Description: Initializing game

java.lang.NoClassDefFoundError: net/arikia/dev/drpc/DiscordEventHandlers$Builder
	at net.sssssssthedev.SmartClient.discord.DiscordMYRPC.start(DiscordMYRPC.java:16)
	at net.sssssssthedev.SmartClient.discord.Client.init(Client.java:15)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:476)
	at net.minecraft.client.Minecraft.run(Minecraft.java:408)
	at net.minecraft.client.main.Main.main(Main.java:113)
Caused by: java.lang.ClassNotFoundException: net.arikia.dev.drpc.DiscordEventHandlers$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.sssssssthedev.SmartClient.discord.DiscordMYRPC.start(DiscordMYRPC.java:16)
	at net.sssssssthedev.SmartClient.discord.Client.init(Client.java:15)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:476)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:408)
	at net.minecraft.client.main.Main.main(Main.java:113)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Windows 10 (amd64) version 10.0
	CPU: <unknown>
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 437843800 bytes (417 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: SmartClient
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: ~~ERROR~~ NullPointerException: null
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

**Comment by sssssssthedev** [comment]
Did you install the libraries needed? This seems like a library issue (Also sorry for late response, haven't checked this repo in a while)

**Comment by sssssssthedev** [comment]
Closed due to no response. As I said above, installing the libraries should fix this
